### ISSUE TITLE
[UI] Search functionality using current location

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#115]
# To DO's

- [x] Only ask for the location of the user when the user actually clicks "Your Current Location"
- [x] Show the dropdown when the user clicks the search input field (i.e., the search input field is on focus)
- [x] Allow up and down using arrow key in dropdown selection
- [x] Fix UI Navigation
- [x] Display Current location inside search input in KYH page when "Your Current Location" is selected and fly to kyh

# Screenshots

## Search Input on Focus
![image](https://user-images.githubusercontent.com/76890692/128833888-9424e07b-633d-4aae-9d0f-e4f67509cf11.png)

## Navigation Old
![image](https://user-images.githubusercontent.com/76890692/128833605-2d96e191-eeb9-4316-8fdf-fe33de0f12e7.png)

## Navigation New
![image](https://user-images.githubusercontent.com/76890692/128833783-3f57812b-9cd7-4f9b-8c48-6020a4af36f3.png)

**Comment by jadurani** [comment]
fixed at https://github.com/UPRI-NOAH/noah-frontend/pull/159
