### ISSUE TITLE
Test multi-source and multi-layer combination

### ISSUE THREAD

**Issue by jadurani** [UPRI-NOAH/noah-frontend#135]
# Summary

In this issue, we'll be exploring the performance of mapbox-gl-js when we use a single tileset for a hazard type-level combo (e.g. flood-100-yr) for the whole Philippines. 

## Sample implementation

https://codepen.io/pfgoting/pen/gORpNbv

**Comment by jadurani** [comment]
# Requested format

```json
{
  "url": "mapbox://prince-test.ph-fh-100yr-tiles",
  "sourceLayers": [
    "PH180000000_FH_100yr",
    "PH170000000_FH_100yr",
    "PH160000000_FH_100yr",
    "PH150000000_FH_100yr",
    "PH140000000_FH_100yr",
    "PH130000000_FH_100yr",
    "PH120000000_FH_100yr",
    "PH110000000_FH_100yr",
    "PH100000000_FH_100yr",
    "PH090000000_FH_100yr",
    "PH080000000_FH_100yr",
    "PH070000000_FH_100yr",
    "PH060000000_FH_100yr",
    "PH050000000_FH_100yr",
    "PH040000000_FH_100yr",
    "PH020000000_FH_100yr"
  ]
}
```

## Basis

![image](https://user-images.githubusercontent.com/11599005/131426201-56db9f07-5104-4e8d-b6b6-f6374a85a09d.png)

**Comment by dichapabe** [comment]
Hello @jadurani, here's the generated JSON of the combined process: https://gist.github.com/dichapabe/70b56e7f1053d9f242b88c864f0f96d6

**Comment by jadurani** [comment]
Waiting on the updated JSON file that has links from the main UPRI mapbox account instead of Prince's account

**Comment by jadurani** [comment]
# Findings

## 1 - Takes 5 seconds to load everything 

![image](https://user-images.githubusercontent.com/11599005/132127670-aa34f2e6-0109-4e71-8789-bf665cd66dc3.png)

## There are no more hiccups when zooming the map in or out 

**Notes**

- The critical facilities are not loaded while testing this. Loading them still causes the page to lag while zooming in or out

![Kapture 2021-09-05 at 21 00 20](https://user-images.githubusercontent.com/11599005/132127784-6ec5b3f7-bb0e-4415-86c0-a9792e66e90f.gif)
