### ISSUE TITLE
Update critical facilities source

### ISSUE THREAD

**Issue by jadurani** [UPRI-NOAH/noah-frontend#141]

**Comment by jadurani** [comment]
@feyeandal @dichapabe add links here please

**Comment by dichapabe** [comment]
Critical Facilities: https://drive.google.com/drive/folders/1wQ2oUFxxIFhtkurx2_8ijEK4J7Tpekj2

**Comment by jadurani** [comment]
Let's have this in s3 too instead of saving the big JSON files in the codebase @dichapabe @pfgoting

**Comment by jadurani** [comment]
Test the json files first

**Comment by jadurani** [comment]
https://noahdev.slack.com/archives/CGP27BHPV/p1631099735003900
