### ISSUE TITLE
WEBM format of Generated HIMAWARI 

### ISSUE THREAD

**Issue by dichapabe** [UPRI-NOAH/noah-frontend#142]
WEBM file:
[ph_himawari.zip](https://github.com/UPRI-NOAH/noah-frontend/files/7133588/ph_himawari.zip)

Map Extent:
lat low - 5.0
lat high - 30.0
long_west - 100.0
long_east - 160.0

**Comment by jadurani** [comment]
Image is kinda off

![image](https://user-images.githubusercontent.com/11599005/132785265-81a72df6-7798-48fd-b96f-130135d3b3ba.png)

**Comment by jadurani** [comment]
Worth exploring too:

- https://blog.mapbox.com/visualizing-radar-data-with-vector-tiles-117bc5ee9a5a
- https://blog.mapbox.com/weather-maps-that-drive-engagement-b8f1f7ce19c9
