### ISSUE TITLE
Use S3 links for static assets

### ISSUE THREAD

**Issue by jadurani** [UPRI-NOAH/noah-frontend#148]
# Pending s3 links from the backend team

- [x] Himawari satellite image
- [x] Contour maps
  - [x] 1hr
  - [x] 6hr
  - [x] 12hr
  - [x] 24hr
  - [x] #169
- [x] PH-wide hazard maps
- [x] PH-wide hazard maps (KYH-specific -- only the extremes)
- [x] PH-wide critical facilities (cleaned and optimized data)

## Notes

It's highly preferable to have direct s3 links to these files instead of having an additional overhead to query an API for a link. This way, I can just reference the s3 link directly on the source like this:

![image](https://user-images.githubusercontent.com/11599005/133009694-e3d69b35-d80f-40d2-8fd0-4d526cb36b1f.png)

([source](https://docs.mapbox.com/mapbox-gl-js/example/external-geojson/))

And this:

![image](https://user-images.githubusercontent.com/11599005/133009732-f0d95635-55f9-40ff-bc1f-bad12b32a06a.png)

([source](https://docs.mapbox.com/mapbox-gl-js/example/video-on-a-map/))

**Comment by jadurani** [comment]
cc @dichapabe @pfgoting

**Comment by dichapabe** [comment]
S3 Links:

- Himawari satellite image - https://upri-noah.s3.ap-southeast-1.amazonaws.com/himawari/ph_himawari.webm
- Contour maps
   - 1hr - https://upri-noah.s3.ap-southeast-1.amazonaws.com/contours/1hr_latest_rainfall_contour.png
   - 3hr - https://upri-noah.s3.ap-southeast-1.amazonaws.com/contours/3hr_latest_rainfall_contour.png
   - 6hr - https://upri-noah.s3.ap-southeast-1.amazonaws.com/contours/6hr_latest_rainfall_contour.png
   - 12hr - https://upri-noah.s3.ap-southeast-1.amazonaws.com/contours/12hr_latest_rainfall_contour.png
   - 24hr - https://upri-noah.s3.ap-southeast-1.amazonaws.com/contours/24hr_latest_rainfall_contour.png
- PH-wide hazard maps - https://upri-noah.s3.ap-southeast-1.amazonaws.com/hazards/ph_combined_tileset.json
