### ISSUE TITLE
Contour Legend Images

### ISSUE THREAD

**Issue by dichapabe** [UPRI-NOAH/noah-frontend#160]
### Contour Legends per Hour

**3hr Rainfall Contour**
![accumulated-rainfall-3](https://user-images.githubusercontent.com/4961067/135212404-9d34b04b-e513-4fa9-8a70-84a40e057fba.png)

**6hr Rainfall Contour**
![accumulated-rainfall-6](https://user-images.githubusercontent.com/4961067/135212408-0552581e-9adc-4b6c-8ab1-c0758b83d48c.png)

**12hr Rainfall Contour**
![accumulated-rainfall-12](https://user-images.githubusercontent.com/4961067/135212409-ff4e9aa2-8b54-463e-8417-fdd34dfcb35d.png)

**24hr Rainfall Contour**
![accumulated-rainfall-24](https://user-images.githubusercontent.com/4961067/135212410-a780beaf-1ef6-4af4-ae77-69d3b6bfe408.png)

Additional Request:
- [x] Rename to `Rainfall Contour` and drop `map`

**Comment by jadurani** [comment]
1. Regarding the contour map legend, would it make sense to display it horizontally?
2. Can we generate this along with the contour map images?

![image](https://user-images.githubusercontent.com/11599005/135226600-a38681e3-fdd9-46a7-9784-f985f5671563.png)

**Comment by jadurani** [comment]
Note that we're missing the legends for 1hr and have reused the one for 3hr for now. Let's fix this right after launch
