### ISSUE TITLE
Add Category for Weather Satellite images

### ISSUE THREAD

**Issue by dichapabe** [UPRI-NOAH/noah-frontend#161]
Add these 2 under Weather Satellite image:
- [ ] HIMAWARI
- [ ] GSMAP

Additional Request:
- [ ] Zoom layer to PAR view

**Comment by jadurani** [comment]
Do we have an s3 link for GSMAP already?

**Comment by dichapabe** [comment]
We don't have yet. But we can add HIMAWARI first to inform the users what satellite image we are displaying.
