### ISSUE TITLE
fix(qc-studio): update Quezon City IOT Sensor tab in Sidebar menu

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#264]
### To dos:
-----

- [x] Change options to checkboxbutton
- [x] Set Flood Sensor as default layer once IOT Sensor is clicked
- [x] Change naming for options for IOT
- [x] Finalize legend color for dots
- [x] Add submenu for Weather
- [x] Add submenu for Flood

**Comment by kennethliporada** [comment]
Done: See PR https://github.com/UPRI-NOAH/noah-frontend/pull/274
