### ISSUE TITLE
fix(qc-studio): [qc-iot-graph] Fix CSS for exit icon/button

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#269]
### To dos:
----

- [x] Fix CSS for x button upper right side of the chart
- [x] Click outside the chart to exit the chart

**Comment by kennethliporada** [comment]
Check PR link [here](https://github.com/UPRI-NOAH/noah-frontend/pull/274#issuecomment-1135583892)

**Comment by kennethliporada** [comment]
check PR link [Here](https://github.com/UPRI-NOAH/noah-frontend/pull/274#issuecomment-1135774221)
