### ISSUE TITLE
fix(kyh): review assessment results to all hazards 

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#281]
### To Do's:
----
-  change the value to `little to none` if no intersection and `unavailable`  id no data

### Screenshots for checking the results
----
![image](https://user-images.githubusercontent.com/76890692/180930206-9d727394-b21f-4511-aee5-fafd70c81688.png)

![295265579_2105746692918076_7784800717708688615_n](https://user-images.githubusercontent.com/76890692/180930333-a07d50b4-b8fe-40eb-86bd-1d6315c61842.jpg)

**Comment by jadurani** [comment]
Hello @bon-carpo,

- kindly add a background/context as to **why**  the action in the ticket description is needed
- I see a PR attached to this github issue. Is there still an action needed for this github issue?
